name: Check Docker Secret
on:
  push:
    branches:
      - main

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Check Docker username secret
        run: |
          echo "Docker username: ${{ secrets.DOCKER_USERNAME }}"
